# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33cf408735523e42eb76cbf2148cbffc4a75b63802b4cca8715210459d498af555d15e678409a61abece5d1b943780ce5f50ab1a92abd02b0774c0ba7a1a5701

test:
  secret_key_base: bff5aeae917e1f5b701c28819d6fb11d18a1a9a1926f7ee33463655e0f9978dd72440c2d5ba57f1b7005ed2518b49326c08777862fb751f0e25151a60ad2cbb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
